//! World Tools Panel
//!
//! Tabbed panel accessible from the pause menu that provides access to
//! development and content creation tools:
//! - Character Generator (layered sprites, stats, factions, dialog)
//! - Sprite Builder (sprite sheet frame definitions)
//! - Factions (faction management, relationships, reputation)
//! - Audio Debug (audio state visualization)
//! - Sound Test (sound browser and preview)
//! - Combat Debug (damage log, frame data, i-frame indicators)

use egui::{Color32, RichText, Ui, Vec2};
use serde::{Deserialize, Serialize};

use super::audio_debug::AudioDebugPanel;
use super::character_generator::CharacterGenerator;
use super::combat_debug::CombatDebug;
use super::factions::FactionsPanel;
use super::sound_test::SoundTestPanel;
use super::sprite_builder::SpriteBuilder;
use super::world_gen_panel::WorldGenPanel;
use super::ScreenConstraints;

// ============================================================================
// World Tools Tabs
// ============================================================================

/// Available tabs in the World Tools panel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum WorldToolsTab {
    /// Character generator with layered sprites, stats, factions, dialog
    #[default]
    CharacterGenerator,
    /// Sprite builder for defining sprite sheet frames
    SpriteBuilder,
    /// Faction management, relationships, and reputation
    Factions,
    /// Audio debug state visualization
    AudioDebug,
    /// Sound browser and preview
    SoundTest,
    /// Combat debug (damage log, frame data)
    CombatDebug,
    /// World generation settings (cubiomes)
    WorldGeneration,
}

impl WorldToolsTab {
    /// Get all available tabs.
    pub fn all() -> &'static [Self] {
        &[
            Self::WorldGeneration,
            Self::CharacterGenerator,
            Self::SpriteBuilder,
            Self::Factions,
            Self::AudioDebug,
            Self::SoundTest,
            Self::CombatDebug,
        ]
    }

    /// Get the display name for this tab.
    pub fn display_name(&self) -> &'static str {
        match self {
            Self::CharacterGenerator => "Characters",
            Self::SpriteBuilder => "Sprites",
            Self::Factions => "Factions",
            Self::AudioDebug => "Audio Debug",
            Self::SoundTest => "Sound Test",
            Self::CombatDebug => "Combat Debug",
            Self::WorldGeneration => "World Gen",
        }
    }

    /// Get the icon for this tab.
    pub fn icon(&self) -> &'static str {
        match self {
            Self::CharacterGenerator => "👤",
            Self::SpriteBuilder => "🎨",
            Self::Factions => "🏴",
            Self::AudioDebug => "🔊",
            Self::SoundTest => "🎵",
            Self::CombatDebug => "⚔",
            Self::WorldGeneration => "🌍",
        }
    }
}

// ============================================================================
// World Tools Actions
// ============================================================================

/// Actions generated by the World Tools panel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WorldToolsAction {
    /// Close the world tools panel
    Close,
}

// ============================================================================
// World Tools State
// ============================================================================

/// World Tools panel state.
pub struct WorldTools {
    /// Whether the panel is visible.
    visible: bool,
    /// Currently active tab.
    active_tab: WorldToolsTab,
    /// Character generator sub-tool.
    character_generator: CharacterGenerator,
    /// Sprite builder sub-tool.
    sprite_builder: SpriteBuilder,
    /// Factions panel sub-tool.
    factions_panel: FactionsPanel,
    /// Audio debug panel sub-tool.
    audio_debug: AudioDebugPanel,
    /// Sound test panel sub-tool.
    sound_test: SoundTestPanel,
    /// Combat debug panel sub-tool.
    combat_debug: CombatDebug,
    /// World generation panel.
    world_gen_panel: WorldGenPanel,
    /// Pending actions.
    actions: Vec<WorldToolsAction>,
}

impl Default for WorldTools {
    fn default() -> Self {
        Self::new()
    }
}

impl WorldTools {
    /// Create a new World Tools panel.
    pub fn new() -> Self {
        // Audio debug and sound test need to be opened when their tab is selected
        let mut audio_debug = AudioDebugPanel::new();
        audio_debug.open();
        let mut sound_test = SoundTestPanel::new();
        sound_test.open();

        Self {
            visible: false,
            active_tab: WorldToolsTab::default(),
            character_generator: CharacterGenerator::new(),
            sprite_builder: SpriteBuilder::new(),
            factions_panel: FactionsPanel::new(),
            audio_debug,
            sound_test,
            combat_debug: CombatDebug::new(),
            world_gen_panel: WorldGenPanel::new(),
            actions: Vec::new(),
        }
    }

    /// Show the panel.
    pub fn show(&mut self) {
        self.visible = true;
    }

    /// Hide the panel.
    pub fn hide(&mut self) {
        self.visible = false;
    }

    /// Check if the panel is visible.
    pub fn is_visible(&self) -> bool {
        self.visible
    }

    /// Select a tab by name (for automation).
    pub fn select_tab_by_name(&mut self, name: &str) {
        let lower = name.to_lowercase();
        for tab in WorldToolsTab::all() {
            if tab.display_name().to_lowercase().contains(&lower) {
                self.active_tab = *tab;
                return;
            }
        }
        tracing::warn!("Unknown world tools tab: {}", name);
    }

    /// Drain all pending actions.
    pub fn drain_actions(&mut self) -> Vec<WorldToolsAction> {
        std::mem::take(&mut self.actions)
    }

    /// Get mutable reference to the world gen panel.
    pub fn world_gen_panel_mut(&mut self) -> &mut WorldGenPanel {
        &mut self.world_gen_panel
    }

    /// Drain world gen actions.
    pub fn drain_world_gen_actions(&mut self) -> Vec<super::world_gen_panel::WorldGenAction> {
        self.world_gen_panel.drain_actions()
    }

    /// Render the World Tools panel.
    pub fn render(&mut self, ui: &mut Ui) {
        let constraints = ScreenConstraints::from_context(ui.ctx());

        let panel_width = constraints.constrained_width(900.0);
        let panel_height = constraints.constrained_height(700.0);

        // Center the panel
        let screen = ui.ctx().screen_rect();
        let panel_x = (screen.width() - panel_width) / 2.0;
        let panel_y = (screen.height() - panel_height) / 2.0;

        ui.allocate_new_ui(
            egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                egui::pos2(panel_x, panel_y),
                Vec2::new(panel_width, panel_height),
            )),
            |ui| {
                egui::Frame::none()
                    .fill(Color32::from_rgb(25, 25, 35))
                    .stroke(egui::Stroke::new(2.0, Color32::from_rgb(80, 80, 120)))
                    .rounding(egui::Rounding::same(8.0))
                    .inner_margin(egui::Margin::same(12.0))
                    .show(ui, |ui| {
                        // Title bar with close button
                        ui.horizontal(|ui| {
                            ui.heading(
                                RichText::new("🛠 World Tools")
                                    .color(Color32::WHITE)
                                    .size(20.0),
                            );
                            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                                if ui
                                    .button(RichText::new("✕").size(18.0).color(Color32::LIGHT_GRAY))
                                    .clicked()
                                {
                                    self.actions.push(WorldToolsAction::Close);
                                }
                            });
                        });

                        ui.add_space(8.0);
                        ui.separator();
                        ui.add_space(4.0);

                        // Tab bar
                        ui.horizontal(|ui| {
                            for tab in WorldToolsTab::all() {
                                let is_active = self.active_tab == *tab;
                                let label = format!("{} {}", tab.icon(), tab.display_name());

                                let button = if is_active {
                                    egui::Button::new(
                                        RichText::new(&label)
                                            .color(Color32::WHITE)
                                            .strong()
                                            .size(14.0),
                                    )
                                    .fill(Color32::from_rgb(60, 60, 100))
                                    .rounding(egui::Rounding::same(4.0))
                                } else {
                                    egui::Button::new(
                                        RichText::new(&label)
                                            .color(Color32::LIGHT_GRAY)
                                            .size(14.0),
                                    )
                                    .fill(Color32::from_rgb(40, 40, 55))
                                    .rounding(egui::Rounding::same(4.0))
                                };

                                if ui.add(button).clicked() {
                                    self.active_tab = *tab;
                                }
                            }
                        });

                        ui.add_space(8.0);
                        ui.separator();
                        ui.add_space(4.0);

                        // Tab content area (scrollable)
                        egui::ScrollArea::both()
                            .auto_shrink([false, false])
                            .show(ui, |ui| {
                                match self.active_tab {
                                    WorldToolsTab::CharacterGenerator => {
                                        self.character_generator.render(ui);
                                    }
                                    WorldToolsTab::SpriteBuilder => {
                                        self.sprite_builder.render(ui);
                                    }
                                    WorldToolsTab::Factions => {
                                        self.factions_panel.render(ui);
                                    }
                                    WorldToolsTab::AudioDebug => {
                                        self.audio_debug.show(ui);
                                    }
                                    WorldToolsTab::SoundTest => {
                                        let _actions = self.sound_test.show(ui);
                                        // Sound test actions (play, stop, etc.) can be
                                        // forwarded to the audio system in the future.
                                    }
                                    WorldToolsTab::CombatDebug => {
                                        // Show the sub-panels that don't need world_to_screen
                                        self.combat_debug.show_damage_log(ui);
                                        ui.add_space(8.0);
                                        self.combat_debug.show_frame_data(ui);
                                        ui.add_space(8.0);
                                        self.combat_debug.show_iframe_indicator(ui);
                                    }
                                    WorldToolsTab::WorldGeneration => {
                                        self.world_gen_panel.render(ui);
                                    }
                                }
                            });
                    });
            },
        );
    }
}
